---
author:
  - 'Ricardo Signes <rjbs@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Addex-Plugin-Nobody
no_index:
  directory:
    - inc
    - t
requires:
  App::Addex: 0.018
  Sub::Install: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.002
